# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A fast implementation of weighted linear regression based on the similar RcppArmadillo implementation.
#'
#' @param X A matrix of independent variables
#' @param y A vector representing the resulting dependent variable
#' @param w A vector of weights of equal length as the number of observations of x and y given to the model.
#' @export
fastLm_impl <- function(X, y, w) {
    .Call(`_blblm_fastLm_impl`, X, y, w)
}

